---
- name: 'prestashop-workspace playbook'
  hosts: all

  tasks:

    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes

    - name: install some useful packages
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - vim
        - unzip
        - tree
        - curl
        - git

    - name: install mysql (server + client + python binding)
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - mysql-server
        - mysql-client
        - python-mysqldb

    - name: create a prestashop mysql user
      mysql_user: name=prestashop password=prestashop priv=*.*:ALL state=present

    - name: install php5
      apt: pkg=php5 state=latest
      sudo: yes

    - name: install php5-mysql binding
      apt: pkg=php5-mysql state=latest
      sudo: yes

    - name: install apache2 http server
      apt: pkg=apache2 state=latest
      sudo: yes

    - name: install apache php5 module
      apt: pkg=libapache2-mod-php5 state=latest
      sudo: yes

    - name: enable apache php5 module
      apache2_module: state=present name=php5

    - name: install phpmyadmin
      apt: pkg=phpmyadmin state=latest
      sudo: yes

    - name: configure phpmyadmin to allow root connection
      copy: src=files/phpmyadmin/config.inc.php dest=/etc/phpmyadmin/config.inc.php
      sudo: yes

    - name: enable phpmyadmin application in apache
      file: src={{ item.src }} dest={{ item.dest }} state=link
      sudo: yes
      with_items:
        - { src: '/etc/phpmyadmin/apache.conf',   dest: '/etc/apache2/sites-available/phpmyadmin' }
        - { src: '../sites-available/phpmyadmin', dest: '/etc/apache2/sites-enabled/001-phpmyadmin' }
      notify:
        - restart apache

    - name: remove apache default index.html page
      file: path=/var/www/index.html state=absent
      sudo: yes

    - name: clone prestashop github repository and submodules
      git: repo=https://github.com/PrestaShop/PrestaShop.git dest=/var/www/ version=1.6.0.6 recursive=yes
      sudo: yes

    - name: set permissions for www directory
      file: path=/var/www group=www-data mode=0775 recurse=yes
      sudo: yes

    - name: install prestashop using cli
      command: /usr/bin/php index_cli.php --domain=prestashopbox --db_user=prestashop --db_password=prestashop --db_create=1 chdir=/var/www/install-dev
      sudo: yes
      notify:
        - restart apache

    - name: ensure apache is running
      service: name=apache2 state=started

  handlers:
    - name: restart apache
      sudo: yes
      service: name=apache2 state=restarted enabled=yes
